//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPSuiteServer {
    using System;
    using System.Collections.Generic;
    using RemObjects.SDK;
    using RemObjects.SDK.Types;
    using RemObjects.DataAbstract.Server;
    
    [System.Serializable()]
    [RemObjects.SDK.Remotable(ActivatorClass=typeof(TFactura_Activator))]
    [System.Reflection.ObfuscationAttribute(Exclude=true)]
    public partial class TFactura : RemObjects.SDK.Types.ComplexType {
        private int @__FacturaID;
        private string @__Serie;
        private int @__Folio;
        private int @__ClienteID;
        private TDetalle[] @__Detalle;
        public virtual int FacturaID {
            get {
                return @__FacturaID;
            }
            set {
                @__FacturaID = value;
                this.TriggerPropertyChanged("FacturaID");
            }
        }
        [RemObjects.SDK.StreamAs(RemObjects.SDK.StreamingFormat.AnsiString)]
        public virtual string Serie {
            get {
                return @__Serie;
            }
            set {
                @__Serie = value;
                this.TriggerPropertyChanged("Serie");
            }
        }
        public virtual int Folio {
            get {
                return @__Folio;
            }
            set {
                @__Folio = value;
                this.TriggerPropertyChanged("Folio");
            }
        }
        public virtual int ClienteID {
            get {
                return @__ClienteID;
            }
            set {
                @__ClienteID = value;
                this.TriggerPropertyChanged("ClienteID");
            }
        }
        public virtual TDetalle[] Detalle {
            get {
                return @__Detalle;
            }
            set {
                @__Detalle = value;
                this.TriggerPropertyChanged("Detalle");
            }
        }
        public override void ReadComplex(RemObjects.SDK.Serializer serializer) {
            if (serializer.RecordStrictOrder) {
                this.FacturaID = serializer.ReadInt32("FacturaID");
                this.Serie = serializer.ReadAnsiString("Serie");
                this.Folio = serializer.ReadInt32("Folio");
                this.ClienteID = serializer.ReadInt32("ClienteID");
                this.Detalle = ((TDetalle[])(serializer.Read("Detalle", typeof(TDetalle[]), RemObjects.SDK.StreamingFormat.Default)));
            }
            else {
                this.ClienteID = serializer.ReadInt32("ClienteID");
                this.Detalle = ((TDetalle[])(serializer.Read("Detalle", typeof(TDetalle[]), RemObjects.SDK.StreamingFormat.Default)));
                this.FacturaID = serializer.ReadInt32("FacturaID");
                this.Folio = serializer.ReadInt32("Folio");
                this.Serie = serializer.ReadAnsiString("Serie");
            }
        }
        public override void WriteComplex(RemObjects.SDK.Serializer serializer) {
            if (serializer.RecordStrictOrder) {
                serializer.WriteInt32("FacturaID", this.FacturaID);
                serializer.WriteAnsiString("Serie", this.Serie);
                serializer.WriteInt32("Folio", this.Folio);
                serializer.WriteInt32("ClienteID", this.ClienteID);
                serializer.Write("Detalle", this.Detalle, typeof(TDetalle[]), RemObjects.SDK.StreamingFormat.Default);
            }
            else {
                serializer.WriteInt32("ClienteID", this.ClienteID);
                serializer.Write("Detalle", this.Detalle, typeof(TDetalle[]), RemObjects.SDK.StreamingFormat.Default);
                serializer.WriteInt32("FacturaID", this.FacturaID);
                serializer.WriteInt32("Folio", this.Folio);
                serializer.WriteAnsiString("Serie", this.Serie);
            }
        }
    }
    [System.Reflection.ObfuscationAttribute(Exclude=true, ApplyToMembers=false)]
    public class TFactura_Activator : object, RemObjects.SDK.ITypeActivator {
        public TFactura_Activator() {
        }
        public object CreateInstance() {
            return new TFactura();
        }
    }
    [System.Serializable()]
    [RemObjects.SDK.Remotable(ActivatorClass=typeof(TDetalle_Activator))]
    [System.Reflection.ObfuscationAttribute(Exclude=true)]
    public partial class TDetalle : RemObjects.SDK.Types.ComplexType {
        private int @__ProductoID;
        private double @__Cantidad;
        private double @__Precio;
        public virtual int ProductoID {
            get {
                return @__ProductoID;
            }
            set {
                @__ProductoID = value;
                this.TriggerPropertyChanged("ProductoID");
            }
        }
        public virtual double Cantidad {
            get {
                return @__Cantidad;
            }
            set {
                @__Cantidad = value;
                this.TriggerPropertyChanged("Cantidad");
            }
        }
        public virtual double Precio {
            get {
                return @__Precio;
            }
            set {
                @__Precio = value;
                this.TriggerPropertyChanged("Precio");
            }
        }
        public override void ReadComplex(RemObjects.SDK.Serializer serializer) {
            if (serializer.RecordStrictOrder) {
                this.ProductoID = serializer.ReadInt32("ProductoID");
                this.Cantidad = serializer.ReadDouble("Cantidad");
                this.Precio = serializer.ReadDouble("Precio");
            }
            else {
                this.Cantidad = serializer.ReadDouble("Cantidad");
                this.Precio = serializer.ReadDouble("Precio");
                this.ProductoID = serializer.ReadInt32("ProductoID");
            }
        }
        public override void WriteComplex(RemObjects.SDK.Serializer serializer) {
            if (serializer.RecordStrictOrder) {
                serializer.WriteInt32("ProductoID", this.ProductoID);
                serializer.WriteDouble("Cantidad", this.Cantidad);
                serializer.WriteDouble("Precio", this.Precio);
            }
            else {
                serializer.WriteDouble("Cantidad", this.Cantidad);
                serializer.WriteDouble("Precio", this.Precio);
                serializer.WriteInt32("ProductoID", this.ProductoID);
            }
        }
    }
    [System.Reflection.ObfuscationAttribute(Exclude=true, ApplyToMembers=false)]
    public class TDetalle_Activator : object, RemObjects.SDK.ITypeActivator {
        public TDetalle_Activator() {
        }
        public object CreateInstance() {
            return new TDetalle();
        }
    }
    [System.Serializable()]
    [RemObjects.SDK.Remotable(ActivatorClass=typeof(TConfiguraEstacion_Activator))]
    [System.Reflection.ObfuscationAttribute(Exclude=true)]
    public partial class TConfiguraEstacion : RemObjects.SDK.Types.ComplexType {
        private int @__Numero;
        private int @__Protocolo;
        private int @__Telemedicion;
        private string @__Nombre;
        private string @__RazonSocial;
        public virtual int Numero {
            get {
                return @__Numero;
            }
            set {
                @__Numero = value;
                this.TriggerPropertyChanged("Numero");
            }
        }
        public virtual int Protocolo {
            get {
                return @__Protocolo;
            }
            set {
                @__Protocolo = value;
                this.TriggerPropertyChanged("Protocolo");
            }
        }
        public virtual int Telemedicion {
            get {
                return @__Telemedicion;
            }
            set {
                @__Telemedicion = value;
                this.TriggerPropertyChanged("Telemedicion");
            }
        }
        [RemObjects.SDK.StreamAs(RemObjects.SDK.StreamingFormat.AnsiString)]
        public virtual string Nombre {
            get {
                return @__Nombre;
            }
            set {
                @__Nombre = value;
                this.TriggerPropertyChanged("Nombre");
            }
        }
        [RemObjects.SDK.StreamAs(RemObjects.SDK.StreamingFormat.AnsiString)]
        public virtual string RazonSocial {
            get {
                return @__RazonSocial;
            }
            set {
                @__RazonSocial = value;
                this.TriggerPropertyChanged("RazonSocial");
            }
        }
        public override void ReadComplex(RemObjects.SDK.Serializer serializer) {
            if (serializer.RecordStrictOrder) {
                this.Numero = serializer.ReadInt32("Numero");
                this.Protocolo = serializer.ReadInt32("Protocolo");
                this.Telemedicion = serializer.ReadInt32("Telemedicion");
                this.Nombre = serializer.ReadAnsiString("Nombre");
                this.RazonSocial = serializer.ReadAnsiString("RazonSocial");
            }
            else {
                this.Nombre = serializer.ReadAnsiString("Nombre");
                this.Numero = serializer.ReadInt32("Numero");
                this.Protocolo = serializer.ReadInt32("Protocolo");
                this.RazonSocial = serializer.ReadAnsiString("RazonSocial");
                this.Telemedicion = serializer.ReadInt32("Telemedicion");
            }
        }
        public override void WriteComplex(RemObjects.SDK.Serializer serializer) {
            if (serializer.RecordStrictOrder) {
                serializer.WriteInt32("Numero", this.Numero);
                serializer.WriteInt32("Protocolo", this.Protocolo);
                serializer.WriteInt32("Telemedicion", this.Telemedicion);
                serializer.WriteAnsiString("Nombre", this.Nombre);
                serializer.WriteAnsiString("RazonSocial", this.RazonSocial);
            }
            else {
                serializer.WriteAnsiString("Nombre", this.Nombre);
                serializer.WriteInt32("Numero", this.Numero);
                serializer.WriteInt32("Protocolo", this.Protocolo);
                serializer.WriteAnsiString("RazonSocial", this.RazonSocial);
                serializer.WriteInt32("Telemedicion", this.Telemedicion);
            }
        }
    }
    [System.Reflection.ObfuscationAttribute(Exclude=true, ApplyToMembers=false)]
    public class TConfiguraEstacion_Activator : object, RemObjects.SDK.ITypeActivator {
        public TConfiguraEstacion_Activator() {
        }
        public object CreateInstance() {
            return new TConfiguraEstacion();
        }
    }
    [System.Serializable()]
    [RemObjects.SDK.Remotable(ActivatorClass=typeof(TConfiguraEstacionBombas_Activator))]
    [System.Reflection.ObfuscationAttribute(Exclude=true)]
    public partial class TConfiguraEstacionBombas : RemObjects.SDK.Types.ComplexType {
        private int @__BombaID;
        private int @__MangueraID;
        private int @__ProductoID;
        public virtual int BombaID {
            get {
                return @__BombaID;
            }
            set {
                @__BombaID = value;
                this.TriggerPropertyChanged("BombaID");
            }
        }
        public virtual int MangueraID {
            get {
                return @__MangueraID;
            }
            set {
                @__MangueraID = value;
                this.TriggerPropertyChanged("MangueraID");
            }
        }
        public virtual int ProductoID {
            get {
                return @__ProductoID;
            }
            set {
                @__ProductoID = value;
                this.TriggerPropertyChanged("ProductoID");
            }
        }
        public override void ReadComplex(RemObjects.SDK.Serializer serializer) {
            if (serializer.RecordStrictOrder) {
                this.BombaID = serializer.ReadInt32("BombaID");
                this.MangueraID = serializer.ReadInt32("MangueraID");
                this.ProductoID = serializer.ReadInt32("ProductoID");
            }
            else {
                this.BombaID = serializer.ReadInt32("BombaID");
                this.MangueraID = serializer.ReadInt32("MangueraID");
                this.ProductoID = serializer.ReadInt32("ProductoID");
            }
        }
        public override void WriteComplex(RemObjects.SDK.Serializer serializer) {
            if (serializer.RecordStrictOrder) {
                serializer.WriteInt32("BombaID", this.BombaID);
                serializer.WriteInt32("MangueraID", this.MangueraID);
                serializer.WriteInt32("ProductoID", this.ProductoID);
            }
            else {
                serializer.WriteInt32("BombaID", this.BombaID);
                serializer.WriteInt32("MangueraID", this.MangueraID);
                serializer.WriteInt32("ProductoID", this.ProductoID);
            }
        }
    }
    [System.Reflection.ObfuscationAttribute(Exclude=true, ApplyToMembers=false)]
    public class TConfiguraEstacionBombas_Activator : object, RemObjects.SDK.ITypeActivator {
        public TConfiguraEstacionBombas_Activator() {
        }
        public object CreateInstance() {
            return new TConfiguraEstacionBombas();
        }
    }
    [System.Serializable()]
    [RemObjects.SDK.Remotable(ActivatorClass=typeof(TConfiguraEstacionTanques_Activator))]
    [System.Reflection.ObfuscationAttribute(Exclude=true)]
    public partial class TConfiguraEstacionTanques : RemObjects.SDK.Types.ComplexType {
        public override void ReadComplex(RemObjects.SDK.Serializer serializer) {
            if (serializer.RecordStrictOrder) {
            }
        }
        public override void WriteComplex(RemObjects.SDK.Serializer serializer) {
            if (serializer.RecordStrictOrder) {
            }
        }
    }
    [System.Reflection.ObfuscationAttribute(Exclude=true, ApplyToMembers=false)]
    public class TConfiguraEstacionTanques_Activator : object, RemObjects.SDK.ITypeActivator {
        public TConfiguraEstacionTanques_Activator() {
        }
        public object CreateInstance() {
            return new TConfiguraEstacionTanques();
        }
    }
    [System.Serializable()]
    [RemObjects.SDK.Remotable(ActivatorClass=typeof(TConfiguraEstacionDispositivos_Activator))]
    [System.Reflection.ObfuscationAttribute(Exclude=true)]
    public partial class TConfiguraEstacionDispositivos : RemObjects.SDK.Types.ComplexType {
        public override void ReadComplex(RemObjects.SDK.Serializer serializer) {
            if (serializer.RecordStrictOrder) {
            }
        }
        public override void WriteComplex(RemObjects.SDK.Serializer serializer) {
            if (serializer.RecordStrictOrder) {
            }
        }
    }
    [System.Reflection.ObfuscationAttribute(Exclude=true, ApplyToMembers=false)]
    public class TConfiguraEstacionDispositivos_Activator : object, RemObjects.SDK.ITypeActivator {
        public TConfiguraEstacionDispositivos_Activator() {
        }
        public object CreateInstance() {
            return new TConfiguraEstacionDispositivos();
        }
    }
    [System.Serializable()]
    [RemObjects.SDK.Remotable(ActivatorClass=typeof(TCliente_Activator))]
    [System.Reflection.ObfuscationAttribute(Exclude=true)]
    public partial class TCliente : RemObjects.SDK.Types.ComplexType {
        private int @__ClienteID;
        private string @__Nombre;
        private string @__RazonSocial;
        private string @__Domicilio;
        private string @__Colonia;
        private string @__Ciudad;
        private string @__Localidad;
        private string @__Estado;
        private string @__CodigoPostal;
        private string @__Telefono;
        private string @__RFC;
        private string @__Estatus;
        private double @__LimiteCredito;
        public virtual int ClienteID {
            get {
                return @__ClienteID;
            }
            set {
                @__ClienteID = value;
                this.TriggerPropertyChanged("ClienteID");
            }
        }
        [RemObjects.SDK.StreamAs(RemObjects.SDK.StreamingFormat.AnsiString)]
        public virtual string Nombre {
            get {
                return @__Nombre;
            }
            set {
                @__Nombre = value;
                this.TriggerPropertyChanged("Nombre");
            }
        }
        [RemObjects.SDK.StreamAs(RemObjects.SDK.StreamingFormat.AnsiString)]
        public virtual string RazonSocial {
            get {
                return @__RazonSocial;
            }
            set {
                @__RazonSocial = value;
                this.TriggerPropertyChanged("RazonSocial");
            }
        }
        [RemObjects.SDK.StreamAs(RemObjects.SDK.StreamingFormat.AnsiString)]
        public virtual string Domicilio {
            get {
                return @__Domicilio;
            }
            set {
                @__Domicilio = value;
                this.TriggerPropertyChanged("Domicilio");
            }
        }
        [RemObjects.SDK.StreamAs(RemObjects.SDK.StreamingFormat.AnsiString)]
        public virtual string Colonia {
            get {
                return @__Colonia;
            }
            set {
                @__Colonia = value;
                this.TriggerPropertyChanged("Colonia");
            }
        }
        [RemObjects.SDK.StreamAs(RemObjects.SDK.StreamingFormat.AnsiString)]
        public virtual string Ciudad {
            get {
                return @__Ciudad;
            }
            set {
                @__Ciudad = value;
                this.TriggerPropertyChanged("Ciudad");
            }
        }
        [RemObjects.SDK.StreamAs(RemObjects.SDK.StreamingFormat.AnsiString)]
        public virtual string Localidad {
            get {
                return @__Localidad;
            }
            set {
                @__Localidad = value;
                this.TriggerPropertyChanged("Localidad");
            }
        }
        [RemObjects.SDK.StreamAs(RemObjects.SDK.StreamingFormat.AnsiString)]
        public virtual string Estado {
            get {
                return @__Estado;
            }
            set {
                @__Estado = value;
                this.TriggerPropertyChanged("Estado");
            }
        }
        [RemObjects.SDK.StreamAs(RemObjects.SDK.StreamingFormat.AnsiString)]
        public virtual string CodigoPostal {
            get {
                return @__CodigoPostal;
            }
            set {
                @__CodigoPostal = value;
                this.TriggerPropertyChanged("CodigoPostal");
            }
        }
        [RemObjects.SDK.StreamAs(RemObjects.SDK.StreamingFormat.AnsiString)]
        public virtual string Telefono {
            get {
                return @__Telefono;
            }
            set {
                @__Telefono = value;
                this.TriggerPropertyChanged("Telefono");
            }
        }
        [RemObjects.SDK.StreamAs(RemObjects.SDK.StreamingFormat.AnsiString)]
        public virtual string RFC {
            get {
                return @__RFC;
            }
            set {
                @__RFC = value;
                this.TriggerPropertyChanged("RFC");
            }
        }
        [RemObjects.SDK.StreamAs(RemObjects.SDK.StreamingFormat.AnsiString)]
        public virtual string Estatus {
            get {
                return @__Estatus;
            }
            set {
                @__Estatus = value;
                this.TriggerPropertyChanged("Estatus");
            }
        }
        public virtual double LimiteCredito {
            get {
                return @__LimiteCredito;
            }
            set {
                @__LimiteCredito = value;
                this.TriggerPropertyChanged("LimiteCredito");
            }
        }
        public override void ReadComplex(RemObjects.SDK.Serializer serializer) {
            if (serializer.RecordStrictOrder) {
                this.ClienteID = serializer.ReadInt32("ClienteID");
                this.Nombre = serializer.ReadAnsiString("Nombre");
                this.RazonSocial = serializer.ReadAnsiString("RazonSocial");
                this.Domicilio = serializer.ReadAnsiString("Domicilio");
                this.Colonia = serializer.ReadAnsiString("Colonia");
                this.Ciudad = serializer.ReadAnsiString("Ciudad");
                this.Localidad = serializer.ReadAnsiString("Localidad");
                this.Estado = serializer.ReadAnsiString("Estado");
                this.CodigoPostal = serializer.ReadAnsiString("CodigoPostal");
                this.Telefono = serializer.ReadAnsiString("Telefono");
                this.RFC = serializer.ReadAnsiString("RFC");
                this.Estatus = serializer.ReadAnsiString("Estatus");
                this.LimiteCredito = serializer.ReadDouble("LimiteCredito");
            }
            else {
                this.Ciudad = serializer.ReadAnsiString("Ciudad");
                this.ClienteID = serializer.ReadInt32("ClienteID");
                this.CodigoPostal = serializer.ReadAnsiString("CodigoPostal");
                this.Colonia = serializer.ReadAnsiString("Colonia");
                this.Domicilio = serializer.ReadAnsiString("Domicilio");
                this.Estado = serializer.ReadAnsiString("Estado");
                this.Estatus = serializer.ReadAnsiString("Estatus");
                this.LimiteCredito = serializer.ReadDouble("LimiteCredito");
                this.Localidad = serializer.ReadAnsiString("Localidad");
                this.Nombre = serializer.ReadAnsiString("Nombre");
                this.RazonSocial = serializer.ReadAnsiString("RazonSocial");
                this.RFC = serializer.ReadAnsiString("RFC");
                this.Telefono = serializer.ReadAnsiString("Telefono");
            }
        }
        public override void WriteComplex(RemObjects.SDK.Serializer serializer) {
            if (serializer.RecordStrictOrder) {
                serializer.WriteInt32("ClienteID", this.ClienteID);
                serializer.WriteAnsiString("Nombre", this.Nombre);
                serializer.WriteAnsiString("RazonSocial", this.RazonSocial);
                serializer.WriteAnsiString("Domicilio", this.Domicilio);
                serializer.WriteAnsiString("Colonia", this.Colonia);
                serializer.WriteAnsiString("Ciudad", this.Ciudad);
                serializer.WriteAnsiString("Localidad", this.Localidad);
                serializer.WriteAnsiString("Estado", this.Estado);
                serializer.WriteAnsiString("CodigoPostal", this.CodigoPostal);
                serializer.WriteAnsiString("Telefono", this.Telefono);
                serializer.WriteAnsiString("RFC", this.RFC);
                serializer.WriteAnsiString("Estatus", this.Estatus);
                serializer.WriteDouble("LimiteCredito", this.LimiteCredito);
            }
            else {
                serializer.WriteAnsiString("Ciudad", this.Ciudad);
                serializer.WriteInt32("ClienteID", this.ClienteID);
                serializer.WriteAnsiString("CodigoPostal", this.CodigoPostal);
                serializer.WriteAnsiString("Colonia", this.Colonia);
                serializer.WriteAnsiString("Domicilio", this.Domicilio);
                serializer.WriteAnsiString("Estado", this.Estado);
                serializer.WriteAnsiString("Estatus", this.Estatus);
                serializer.WriteDouble("LimiteCredito", this.LimiteCredito);
                serializer.WriteAnsiString("Localidad", this.Localidad);
                serializer.WriteAnsiString("Nombre", this.Nombre);
                serializer.WriteAnsiString("RazonSocial", this.RazonSocial);
                serializer.WriteAnsiString("RFC", this.RFC);
                serializer.WriteAnsiString("Telefono", this.Telefono);
            }
        }
    }
    [System.Reflection.ObfuscationAttribute(Exclude=true, ApplyToMembers=false)]
    public class TCliente_Activator : object, RemObjects.SDK.ITypeActivator {
        public TCliente_Activator() {
        }
        public object CreateInstance() {
            return new TCliente();
        }
    }
    [System.Serializable()]
    [RemObjects.SDK.Remotable(ActivatorClass=typeof(TVehiculo_Activator))]
    [System.Reflection.ObfuscationAttribute(Exclude=true)]
    public partial class TVehiculo : RemObjects.SDK.Types.ComplexType {
        private int @__VehiculoID;
        private string @__Nip;
        private string @__Status;
        private int @__CargasMaximas;
        private double @__LimiteLTDia;
        private double @__LimiteLTSemana;
        private double @__LimiteLTMes;
        private double @__LimiteMNDia;
        private double @__LimiteMNSemana;
        private double @__LimiteMNMes;
        private string @__Lunes;
        private string @__Martes;
        private string @__Miercoles;
        private string @__Jueves;
        private string @__Viernes;
        private string @__Sabado;
        private string @__Domingo;
        private string @__ProductoAutorizado;
        private string @__Estacion;
        public virtual int VehiculoID {
            get {
                return @__VehiculoID;
            }
            set {
                @__VehiculoID = value;
                this.TriggerPropertyChanged("VehiculoID");
            }
        }
        [RemObjects.SDK.StreamAs(RemObjects.SDK.StreamingFormat.AnsiString)]
        public virtual string Nip {
            get {
                return @__Nip;
            }
            set {
                @__Nip = value;
                this.TriggerPropertyChanged("Nip");
            }
        }
        [RemObjects.SDK.StreamAs(RemObjects.SDK.StreamingFormat.AnsiString)]
        public virtual string Status {
            get {
                return @__Status;
            }
            set {
                @__Status = value;
                this.TriggerPropertyChanged("Status");
            }
        }
        public virtual int CargasMaximas {
            get {
                return @__CargasMaximas;
            }
            set {
                @__CargasMaximas = value;
                this.TriggerPropertyChanged("CargasMaximas");
            }
        }
        public virtual double LimiteLTDia {
            get {
                return @__LimiteLTDia;
            }
            set {
                @__LimiteLTDia = value;
                this.TriggerPropertyChanged("LimiteLTDia");
            }
        }
        public virtual double LimiteLTSemana {
            get {
                return @__LimiteLTSemana;
            }
            set {
                @__LimiteLTSemana = value;
                this.TriggerPropertyChanged("LimiteLTSemana");
            }
        }
        public virtual double LimiteLTMes {
            get {
                return @__LimiteLTMes;
            }
            set {
                @__LimiteLTMes = value;
                this.TriggerPropertyChanged("LimiteLTMes");
            }
        }
        public virtual double LimiteMNDia {
            get {
                return @__LimiteMNDia;
            }
            set {
                @__LimiteMNDia = value;
                this.TriggerPropertyChanged("LimiteMNDia");
            }
        }
        public virtual double LimiteMNSemana {
            get {
                return @__LimiteMNSemana;
            }
            set {
                @__LimiteMNSemana = value;
                this.TriggerPropertyChanged("LimiteMNSemana");
            }
        }
        public virtual double LimiteMNMes {
            get {
                return @__LimiteMNMes;
            }
            set {
                @__LimiteMNMes = value;
                this.TriggerPropertyChanged("LimiteMNMes");
            }
        }
        [RemObjects.SDK.StreamAs(RemObjects.SDK.StreamingFormat.AnsiString)]
        public virtual string Lunes {
            get {
                return @__Lunes;
            }
            set {
                @__Lunes = value;
                this.TriggerPropertyChanged("Lunes");
            }
        }
        [RemObjects.SDK.StreamAs(RemObjects.SDK.StreamingFormat.AnsiString)]
        public virtual string Martes {
            get {
                return @__Martes;
            }
            set {
                @__Martes = value;
                this.TriggerPropertyChanged("Martes");
            }
        }
        [RemObjects.SDK.StreamAs(RemObjects.SDK.StreamingFormat.AnsiString)]
        public virtual string Miercoles {
            get {
                return @__Miercoles;
            }
            set {
                @__Miercoles = value;
                this.TriggerPropertyChanged("Miercoles");
            }
        }
        [RemObjects.SDK.StreamAs(RemObjects.SDK.StreamingFormat.AnsiString)]
        public virtual string Jueves {
            get {
                return @__Jueves;
            }
            set {
                @__Jueves = value;
                this.TriggerPropertyChanged("Jueves");
            }
        }
        [RemObjects.SDK.StreamAs(RemObjects.SDK.StreamingFormat.AnsiString)]
        public virtual string Viernes {
            get {
                return @__Viernes;
            }
            set {
                @__Viernes = value;
                this.TriggerPropertyChanged("Viernes");
            }
        }
        [RemObjects.SDK.StreamAs(RemObjects.SDK.StreamingFormat.AnsiString)]
        public virtual string Sabado {
            get {
                return @__Sabado;
            }
            set {
                @__Sabado = value;
                this.TriggerPropertyChanged("Sabado");
            }
        }
        [RemObjects.SDK.StreamAs(RemObjects.SDK.StreamingFormat.AnsiString)]
        public virtual string Domingo {
            get {
                return @__Domingo;
            }
            set {
                @__Domingo = value;
                this.TriggerPropertyChanged("Domingo");
            }
        }
        [RemObjects.SDK.StreamAs(RemObjects.SDK.StreamingFormat.AnsiString)]
        public virtual string ProductoAutorizado {
            get {
                return @__ProductoAutorizado;
            }
            set {
                @__ProductoAutorizado = value;
                this.TriggerPropertyChanged("ProductoAutorizado");
            }
        }
        [RemObjects.SDK.StreamAs(RemObjects.SDK.StreamingFormat.AnsiString)]
        public virtual string Estacion {
            get {
                return @__Estacion;
            }
            set {
                @__Estacion = value;
                this.TriggerPropertyChanged("Estacion");
            }
        }
        public override void ReadComplex(RemObjects.SDK.Serializer serializer) {
            if (serializer.RecordStrictOrder) {
                this.VehiculoID = serializer.ReadInt32("VehiculoID");
                this.Nip = serializer.ReadAnsiString("Nip");
                this.Status = serializer.ReadAnsiString("Status");
                this.CargasMaximas = serializer.ReadInt32("CargasMaximas");
                this.LimiteLTDia = serializer.ReadDouble("LimiteLTDia");
                this.LimiteLTSemana = serializer.ReadDouble("LimiteLTSemana");
                this.LimiteLTMes = serializer.ReadDouble("LimiteLTMes");
                this.LimiteMNDia = serializer.ReadDouble("LimiteMNDia");
                this.LimiteMNSemana = serializer.ReadDouble("LimiteMNSemana");
                this.LimiteMNMes = serializer.ReadDouble("LimiteMNMes");
                this.Lunes = serializer.ReadAnsiString("Lunes");
                this.Martes = serializer.ReadAnsiString("Martes");
                this.Miercoles = serializer.ReadAnsiString("Miercoles");
                this.Jueves = serializer.ReadAnsiString("Jueves");
                this.Viernes = serializer.ReadAnsiString("Viernes");
                this.Sabado = serializer.ReadAnsiString("Sabado");
                this.Domingo = serializer.ReadAnsiString("Domingo");
                this.ProductoAutorizado = serializer.ReadAnsiString("ProductoAutorizado");
                this.Estacion = serializer.ReadAnsiString("Estacion");
            }
            else {
                this.CargasMaximas = serializer.ReadInt32("CargasMaximas");
                this.Domingo = serializer.ReadAnsiString("Domingo");
                this.Estacion = serializer.ReadAnsiString("Estacion");
                this.Jueves = serializer.ReadAnsiString("Jueves");
                this.LimiteLTDia = serializer.ReadDouble("LimiteLTDia");
                this.LimiteLTMes = serializer.ReadDouble("LimiteLTMes");
                this.LimiteLTSemana = serializer.ReadDouble("LimiteLTSemana");
                this.LimiteMNDia = serializer.ReadDouble("LimiteMNDia");
                this.LimiteMNMes = serializer.ReadDouble("LimiteMNMes");
                this.LimiteMNSemana = serializer.ReadDouble("LimiteMNSemana");
                this.Lunes = serializer.ReadAnsiString("Lunes");
                this.Martes = serializer.ReadAnsiString("Martes");
                this.Miercoles = serializer.ReadAnsiString("Miercoles");
                this.Nip = serializer.ReadAnsiString("Nip");
                this.ProductoAutorizado = serializer.ReadAnsiString("ProductoAutorizado");
                this.Sabado = serializer.ReadAnsiString("Sabado");
                this.Status = serializer.ReadAnsiString("Status");
                this.VehiculoID = serializer.ReadInt32("VehiculoID");
                this.Viernes = serializer.ReadAnsiString("Viernes");
            }
        }
        public override void WriteComplex(RemObjects.SDK.Serializer serializer) {
            if (serializer.RecordStrictOrder) {
                serializer.WriteInt32("VehiculoID", this.VehiculoID);
                serializer.WriteAnsiString("Nip", this.Nip);
                serializer.WriteAnsiString("Status", this.Status);
                serializer.WriteInt32("CargasMaximas", this.CargasMaximas);
                serializer.WriteDouble("LimiteLTDia", this.LimiteLTDia);
                serializer.WriteDouble("LimiteLTSemana", this.LimiteLTSemana);
                serializer.WriteDouble("LimiteLTMes", this.LimiteLTMes);
                serializer.WriteDouble("LimiteMNDia", this.LimiteMNDia);
                serializer.WriteDouble("LimiteMNSemana", this.LimiteMNSemana);
                serializer.WriteDouble("LimiteMNMes", this.LimiteMNMes);
                serializer.WriteAnsiString("Lunes", this.Lunes);
                serializer.WriteAnsiString("Martes", this.Martes);
                serializer.WriteAnsiString("Miercoles", this.Miercoles);
                serializer.WriteAnsiString("Jueves", this.Jueves);
                serializer.WriteAnsiString("Viernes", this.Viernes);
                serializer.WriteAnsiString("Sabado", this.Sabado);
                serializer.WriteAnsiString("Domingo", this.Domingo);
                serializer.WriteAnsiString("ProductoAutorizado", this.ProductoAutorizado);
                serializer.WriteAnsiString("Estacion", this.Estacion);
            }
            else {
                serializer.WriteInt32("CargasMaximas", this.CargasMaximas);
                serializer.WriteAnsiString("Domingo", this.Domingo);
                serializer.WriteAnsiString("Estacion", this.Estacion);
                serializer.WriteAnsiString("Jueves", this.Jueves);
                serializer.WriteDouble("LimiteLTDia", this.LimiteLTDia);
                serializer.WriteDouble("LimiteLTMes", this.LimiteLTMes);
                serializer.WriteDouble("LimiteLTSemana", this.LimiteLTSemana);
                serializer.WriteDouble("LimiteMNDia", this.LimiteMNDia);
                serializer.WriteDouble("LimiteMNMes", this.LimiteMNMes);
                serializer.WriteDouble("LimiteMNSemana", this.LimiteMNSemana);
                serializer.WriteAnsiString("Lunes", this.Lunes);
                serializer.WriteAnsiString("Martes", this.Martes);
                serializer.WriteAnsiString("Miercoles", this.Miercoles);
                serializer.WriteAnsiString("Nip", this.Nip);
                serializer.WriteAnsiString("ProductoAutorizado", this.ProductoAutorizado);
                serializer.WriteAnsiString("Sabado", this.Sabado);
                serializer.WriteAnsiString("Status", this.Status);
                serializer.WriteInt32("VehiculoID", this.VehiculoID);
                serializer.WriteAnsiString("Viernes", this.Viernes);
            }
        }
    }
    [System.Reflection.ObfuscationAttribute(Exclude=true, ApplyToMembers=false)]
    public class TVehiculo_Activator : object, RemObjects.SDK.ITypeActivator {
        public TVehiculo_Activator() {
        }
        public object CreateInstance() {
            return new TVehiculo();
        }
    }
    [System.Serializable()]
    [RemObjects.SDK.Remotable(ActivatorClass=typeof(TUsuarioWeb_Activator))]
    [System.Reflection.ObfuscationAttribute(Exclude=true)]
    public partial class TUsuarioWeb : RemObjects.SDK.Types.ComplexType {
        private int @__UsuarioWebID;
        private string @__Nombre;
        private string @__Usuario;
        private string @__Clave;
        private bool @__Administrador;
        private int @__ClienteID;
        public virtual int UsuarioWebID {
            get {
                return @__UsuarioWebID;
            }
            set {
                @__UsuarioWebID = value;
                this.TriggerPropertyChanged("UsuarioWebID");
            }
        }
        [RemObjects.SDK.StreamAs(RemObjects.SDK.StreamingFormat.AnsiString)]
        public virtual string Nombre {
            get {
                return @__Nombre;
            }
            set {
                @__Nombre = value;
                this.TriggerPropertyChanged("Nombre");
            }
        }
        [RemObjects.SDK.StreamAs(RemObjects.SDK.StreamingFormat.AnsiString)]
        public virtual string Usuario {
            get {
                return @__Usuario;
            }
            set {
                @__Usuario = value;
                this.TriggerPropertyChanged("Usuario");
            }
        }
        [RemObjects.SDK.StreamAs(RemObjects.SDK.StreamingFormat.AnsiString)]
        public virtual string Clave {
            get {
                return @__Clave;
            }
            set {
                @__Clave = value;
                this.TriggerPropertyChanged("Clave");
            }
        }
        public virtual bool Administrador {
            get {
                return @__Administrador;
            }
            set {
                @__Administrador = value;
                this.TriggerPropertyChanged("Administrador");
            }
        }
        public virtual int ClienteID {
            get {
                return @__ClienteID;
            }
            set {
                @__ClienteID = value;
                this.TriggerPropertyChanged("ClienteID");
            }
        }
        public override void ReadComplex(RemObjects.SDK.Serializer serializer) {
            if (serializer.RecordStrictOrder) {
                this.UsuarioWebID = serializer.ReadInt32("UsuarioWebID");
                this.Nombre = serializer.ReadAnsiString("Nombre");
                this.Usuario = serializer.ReadAnsiString("Usuario");
                this.Clave = serializer.ReadAnsiString("Clave");
                this.Administrador = serializer.ReadBoolean("Administrador");
                this.ClienteID = serializer.ReadInt32("ClienteID");
            }
            else {
                this.Administrador = serializer.ReadBoolean("Administrador");
                this.Clave = serializer.ReadAnsiString("Clave");
                this.ClienteID = serializer.ReadInt32("ClienteID");
                this.Nombre = serializer.ReadAnsiString("Nombre");
                this.Usuario = serializer.ReadAnsiString("Usuario");
                this.UsuarioWebID = serializer.ReadInt32("UsuarioWebID");
            }
        }
        public override void WriteComplex(RemObjects.SDK.Serializer serializer) {
            if (serializer.RecordStrictOrder) {
                serializer.WriteInt32("UsuarioWebID", this.UsuarioWebID);
                serializer.WriteAnsiString("Nombre", this.Nombre);
                serializer.WriteAnsiString("Usuario", this.Usuario);
                serializer.WriteAnsiString("Clave", this.Clave);
                serializer.WriteBoolean("Administrador", this.Administrador);
                serializer.WriteInt32("ClienteID", this.ClienteID);
            }
            else {
                serializer.WriteBoolean("Administrador", this.Administrador);
                serializer.WriteAnsiString("Clave", this.Clave);
                serializer.WriteInt32("ClienteID", this.ClienteID);
                serializer.WriteAnsiString("Nombre", this.Nombre);
                serializer.WriteAnsiString("Usuario", this.Usuario);
                serializer.WriteInt32("UsuarioWebID", this.UsuarioWebID);
            }
        }
    }
    [System.Reflection.ObfuscationAttribute(Exclude=true, ApplyToMembers=false)]
    public class TUsuarioWeb_Activator : object, RemObjects.SDK.ITypeActivator {
        public TUsuarioWeb_Activator() {
        }
        public object CreateInstance() {
            return new TUsuarioWeb();
        }
    }
    public interface IRPLoginService : RemObjects.DataAbstract.Server.ISimpleLoginService {
    }
    public partial class RPLoginService_Proxy : RemObjects.DataAbstract.Server.SimpleLoginService_Proxy, IRPLoginService {
        public RPLoginService_Proxy(RemObjects.SDK.IMessage message, RemObjects.SDK.IClientChannel clientChannel) : 
                base(message, clientChannel) {
        }
        public RPLoginService_Proxy(RemObjects.SDK.IMessage message, RemObjects.SDK.IClientChannel clientChannel, string interfaceName) : 
                base(message, clientChannel, interfaceName) {
        }
        public RPLoginService_Proxy(RemObjects.SDK.IRemoteService remoteService) : 
                base(remoteService) {
        }
        public RPLoginService_Proxy(RemObjects.SDK.IRemoteService remoteService, string interfaceName) : 
                base(remoteService, interfaceName) {
        }
        public RPLoginService_Proxy(System.Uri uri) : 
                base(uri) {
        }
        public RPLoginService_Proxy(string url) : 
                base(url) {
        }
        public override string InterfaceName {
            get {
                return "RPLoginService";
            }
        }
    }
    public class CoRPLoginService {
        public static IRPLoginService Create(RemObjects.SDK.IMessage message, RemObjects.SDK.IClientChannel clientChannel) {
            return new RPLoginService_Proxy(message, clientChannel);
        }
        public static IRPLoginService Create(RemObjects.SDK.IRemoteService remoteService) {
            return new RPLoginService_Proxy(remoteService);
        }
        public static IRPLoginService Create(System.Uri uri) {
            return new RPLoginService_Proxy(uri);
        }
        public static IRPLoginService Create(string url) {
            return new RPLoginService_Proxy(url);
        }
    }
    public interface IRPLoginService_Async : RemObjects.DataAbstract.Server.ISimpleLoginService_Async {
    }
    public partial class RPLoginService_AsyncProxy : RemObjects.DataAbstract.Server.SimpleLoginService_AsyncProxy, IRPLoginService_Async {
        public RPLoginService_AsyncProxy(RemObjects.SDK.IMessage message, RemObjects.SDK.IClientChannel clientChannel) : 
                base(message, clientChannel) {
        }
        public RPLoginService_AsyncProxy(RemObjects.SDK.IMessage message, RemObjects.SDK.IClientChannel clientChannel, string interfaceName) : 
                base(message, clientChannel, interfaceName) {
        }
        public RPLoginService_AsyncProxy(RemObjects.SDK.IRemoteService remoteService) : 
                base(remoteService) {
        }
        public RPLoginService_AsyncProxy(RemObjects.SDK.IRemoteService remoteService, string interfaceName) : 
                base(remoteService, interfaceName) {
        }
        public RPLoginService_AsyncProxy(System.Uri uri) : 
                base(uri) {
        }
        public RPLoginService_AsyncProxy(string url) : 
                base(url) {
        }
        public override string InterfaceName {
            get {
                return "RPLoginService";
            }
        }
    }
    public class CoRPLoginServiceAsync {
        public static IRPLoginService_Async Create(RemObjects.SDK.IMessage message, RemObjects.SDK.IClientChannel clientChannel) {
            return new RPLoginService_AsyncProxy(message, clientChannel);
        }
        public static IRPLoginService_Async Create(RemObjects.SDK.IRemoteService remoteService) {
            return new RPLoginService_AsyncProxy(remoteService);
        }
        public static IRPLoginService_Async Create(System.Uri uri) {
            return new RPLoginService_AsyncProxy(uri);
        }
        public static IRPLoginService_Async Create(string url) {
            return new RPLoginService_AsyncProxy(url);
        }
    }
    public interface IRPDataService : RemObjects.DataAbstract.Server.IDataAbstractService {
        bool GuardaFactura(TFactura Datos);
        System.DateTime Fecha();
        int SPGetFolio(string Datos);
        int Folio(string Campo, string Serie);
        string getGasolinero();
        TCliente getCliente(int ClienteID);
        bool UpdateVehiculo(TVehiculo Datos);
        bool UpdateUsuarioWeb(TUsuarioWeb Datos);
        bool setUsuarioWeb(TUsuarioWeb Datos);
    }
    public partial class RPDataService_Proxy : RemObjects.DataAbstract.Server.DataAbstractService_Proxy, IRPDataService {
        public RPDataService_Proxy(RemObjects.SDK.IMessage message, RemObjects.SDK.IClientChannel clientChannel) : 
                base(message, clientChannel) {
        }
        public RPDataService_Proxy(RemObjects.SDK.IMessage message, RemObjects.SDK.IClientChannel clientChannel, string interfaceName) : 
                base(message, clientChannel, interfaceName) {
        }
        public RPDataService_Proxy(RemObjects.SDK.IRemoteService remoteService) : 
                base(remoteService) {
        }
        public RPDataService_Proxy(RemObjects.SDK.IRemoteService remoteService, string interfaceName) : 
                base(remoteService, interfaceName) {
        }
        public RPDataService_Proxy(System.Uri uri) : 
                base(uri) {
        }
        public RPDataService_Proxy(string url) : 
                base(url) {
        }
        public override string InterfaceName {
            get {
                return "RPDataService";
            }
        }
        public virtual bool GuardaFactura(TFactura Datos) {
            RemObjects.SDK.IMessage @__LocalMessage = this.@__GetMessage();
            try {
                @__LocalMessage.InitializeRequestMessage(this.ClientChannel, "RPSuiteServer", this.ActiveInterfaceName, "GuardaFactura");
                @__LocalMessage.Write("Datos", Datos, typeof(TFactura), RemObjects.SDK.StreamingFormat.Default);
                @__LocalMessage.FinalizeMessage();
                this.ClientChannel.Dispatch(@__LocalMessage);
                bool _Result = @__LocalMessage.ReadBoolean("Result");
                return _Result;
            }
            finally {
                this.@__ClearMessage(@__LocalMessage);
            }
        }
        public virtual System.DateTime Fecha() {
            RemObjects.SDK.IMessage @__LocalMessage = this.@__GetMessage();
            try {
                @__LocalMessage.InitializeRequestMessage(this.ClientChannel, "RPSuiteServer", this.ActiveInterfaceName, "Fecha");
                @__LocalMessage.FinalizeMessage();
                this.ClientChannel.Dispatch(@__LocalMessage);
                System.DateTime _Result = @__LocalMessage.ReadDateTime("Result");
                return _Result;
            }
            finally {
                this.@__ClearMessage(@__LocalMessage);
            }
        }
        public virtual int SPGetFolio(string Datos) {
            RemObjects.SDK.IMessage @__LocalMessage = this.@__GetMessage();
            try {
                @__LocalMessage.InitializeRequestMessage(this.ClientChannel, "RPSuiteServer", this.ActiveInterfaceName, "SPGetFolio");
                @__LocalMessage.WriteAnsiString("Datos", Datos);
                @__LocalMessage.FinalizeMessage();
                this.ClientChannel.Dispatch(@__LocalMessage);
                int _Result = @__LocalMessage.ReadInt32("Result");
                return _Result;
            }
            finally {
                this.@__ClearMessage(@__LocalMessage);
            }
        }
        public virtual int Folio(string Campo, string Serie) {
            RemObjects.SDK.IMessage @__LocalMessage = this.@__GetMessage();
            try {
                @__LocalMessage.InitializeRequestMessage(this.ClientChannel, "RPSuiteServer", this.ActiveInterfaceName, "Folio");
                @__LocalMessage.WriteAnsiString("Campo", Campo);
                @__LocalMessage.WriteAnsiString("Serie", Serie);
                @__LocalMessage.FinalizeMessage();
                this.ClientChannel.Dispatch(@__LocalMessage);
                int _Result = @__LocalMessage.ReadInt32("Result");
                return _Result;
            }
            finally {
                this.@__ClearMessage(@__LocalMessage);
            }
        }
        public virtual string getGasolinero() {
            RemObjects.SDK.IMessage @__LocalMessage = this.@__GetMessage();
            try {
                @__LocalMessage.InitializeRequestMessage(this.ClientChannel, "RPSuiteServer", this.ActiveInterfaceName, "getGasolinero");
                @__LocalMessage.FinalizeMessage();
                this.ClientChannel.Dispatch(@__LocalMessage);
                string _Result = @__LocalMessage.ReadAnsiString("Result");
                return _Result;
            }
            finally {
                this.@__ClearMessage(@__LocalMessage);
            }
        }
        public virtual TCliente getCliente(int ClienteID) {
            RemObjects.SDK.IMessage @__LocalMessage = this.@__GetMessage();
            try {
                @__LocalMessage.InitializeRequestMessage(this.ClientChannel, "RPSuiteServer", this.ActiveInterfaceName, "getCliente");
                @__LocalMessage.WriteInt32("ClienteID", ClienteID);
                @__LocalMessage.FinalizeMessage();
                this.ClientChannel.Dispatch(@__LocalMessage);
                TCliente _Result = ((TCliente)(@__LocalMessage.Read("Result", typeof(TCliente), RemObjects.SDK.StreamingFormat.Default)));
                return _Result;
            }
            finally {
                this.@__ClearMessage(@__LocalMessage);
            }
        }
        public virtual bool UpdateVehiculo(TVehiculo Datos) {
            RemObjects.SDK.IMessage @__LocalMessage = this.@__GetMessage();
            try {
                @__LocalMessage.InitializeRequestMessage(this.ClientChannel, "RPSuiteServer", this.ActiveInterfaceName, "UpdateVehiculo");
                @__LocalMessage.Write("Datos", Datos, typeof(TVehiculo), RemObjects.SDK.StreamingFormat.Default);
                @__LocalMessage.FinalizeMessage();
                this.ClientChannel.Dispatch(@__LocalMessage);
                bool _Result = @__LocalMessage.ReadBoolean("Result");
                return _Result;
            }
            finally {
                this.@__ClearMessage(@__LocalMessage);
            }
        }
        public virtual bool UpdateUsuarioWeb(TUsuarioWeb Datos)
        {
            RemObjects.SDK.IMessage @__LocalMessage = this.@__GetMessage();
            try
            {
                @__LocalMessage.InitializeRequestMessage(this.ClientChannel, "RPSuiteServer", this.ActiveInterfaceName, "UpdateUsuarioWeb");
                @__LocalMessage.Write("Datos", Datos, typeof(TVehiculo), RemObjects.SDK.StreamingFormat.Default);
                @__LocalMessage.FinalizeMessage();
                this.ClientChannel.Dispatch(@__LocalMessage);
                bool _Result = @__LocalMessage.ReadBoolean("Result");
                return _Result;
            }
            finally
            {
                this.@__ClearMessage(@__LocalMessage);
            }
        }

        public virtual bool setUsuarioWeb(TUsuarioWeb Datos)
        {
            RemObjects.SDK.IMessage @__LocalMessage = this.@__GetMessage();
            try
            {
                @__LocalMessage.InitializeRequestMessage(this.ClientChannel, "RPSuiteServer", this.ActiveInterfaceName, "setUsuarioWeb");
                @__LocalMessage.Write("Datos", Datos, typeof(TVehiculo), RemObjects.SDK.StreamingFormat.Default);
                @__LocalMessage.FinalizeMessage();
                this.ClientChannel.Dispatch(@__LocalMessage);
                bool _Result = @__LocalMessage.ReadBoolean("Result");
                return _Result;
            }
            finally
            {
                this.@__ClearMessage(@__LocalMessage);
            }
        }
    }
    public class CoRPDataService {
        public static IRPDataService Create(RemObjects.SDK.IMessage message, RemObjects.SDK.IClientChannel clientChannel) {
            return new RPDataService_Proxy(message, clientChannel);
        }
        public static IRPDataService Create(RemObjects.SDK.IRemoteService remoteService) {
            return new RPDataService_Proxy(remoteService);
        }
        public static IRPDataService Create(System.Uri uri) {
            return new RPDataService_Proxy(uri);
        }
        public static IRPDataService Create(string url) {
            return new RPDataService_Proxy(url);
        }
    }
    public interface IRPDataService_Async : RemObjects.DataAbstract.Server.IDataAbstractService_Async {
        System.IAsyncResult BeginGuardaFactura(TFactura Datos, System.AsyncCallback @__Callback, object @__UserData);
        bool EndGuardaFactura(System.IAsyncResult @__AsyncResult);
        System.Threading.Tasks.Task<bool> GuardaFacturaAsync(TFactura Datos);
        System.IAsyncResult BeginFecha(System.AsyncCallback @__Callback, object @__UserData);
        System.DateTime EndFecha(System.IAsyncResult @__AsyncResult);
        System.Threading.Tasks.Task<System.DateTime> FechaAsync();
        System.IAsyncResult BeginSPGetFolio(string Datos, System.AsyncCallback @__Callback, object @__UserData);
        int EndSPGetFolio(System.IAsyncResult @__AsyncResult);
        System.Threading.Tasks.Task<int> SPGetFolioAsync(string Datos);
        System.IAsyncResult BeginFolio(string Campo, string Serie, System.AsyncCallback @__Callback, object @__UserData);
        int EndFolio(System.IAsyncResult @__AsyncResult);
        System.Threading.Tasks.Task<int> FolioAsync(string Campo, string Serie);
        System.IAsyncResult BegingetGasolinero(System.AsyncCallback @__Callback, object @__UserData);
        string EndgetGasolinero(System.IAsyncResult @__AsyncResult);
        System.Threading.Tasks.Task<string> getGasolineroAsync();
        System.IAsyncResult BegingetCliente(int ClienteID, System.AsyncCallback @__Callback, object @__UserData);
        TCliente EndgetCliente(System.IAsyncResult @__AsyncResult);
        System.Threading.Tasks.Task<TCliente> getClienteAsync(int ClienteID);
        System.IAsyncResult BeginUpdateVehiculo(TVehiculo Datos, System.AsyncCallback @__Callback, object @__UserData);
        bool EndUpdateVehiculo(System.IAsyncResult @__AsyncResult);
        System.Threading.Tasks.Task<bool> UpdateVehiculoAsync(TVehiculo Datos);
    }
    public partial class RPDataService_AsyncProxy : RemObjects.DataAbstract.Server.DataAbstractService_AsyncProxy, IRPDataService_Async {
        public RPDataService_AsyncProxy(RemObjects.SDK.IMessage message, RemObjects.SDK.IClientChannel clientChannel) : 
                base(message, clientChannel) {
        }
        public RPDataService_AsyncProxy(RemObjects.SDK.IMessage message, RemObjects.SDK.IClientChannel clientChannel, string interfaceName) : 
                base(message, clientChannel, interfaceName) {
        }
        public RPDataService_AsyncProxy(RemObjects.SDK.IRemoteService remoteService) : 
                base(remoteService) {
        }
        public RPDataService_AsyncProxy(RemObjects.SDK.IRemoteService remoteService, string interfaceName) : 
                base(remoteService, interfaceName) {
        }
        public RPDataService_AsyncProxy(System.Uri uri) : 
                base(uri) {
        }
        public RPDataService_AsyncProxy(string url) : 
                base(url) {
        }
        public override string InterfaceName {
            get {
                return "RPDataService";
            }
        }
        public virtual System.IAsyncResult BeginGuardaFactura(TFactura Datos, System.AsyncCallback @__Callback, object @__UserData) {
            RemObjects.SDK.IMessage @__LocalMessage = this.@__GetMessage();
            try {
                @__LocalMessage.InitializeRequestMessage(this.ClientChannel, "RPSuiteServer", this.ActiveInterfaceName, "GuardaFactura");
                @__LocalMessage.Write("Datos", Datos, typeof(TFactura), RemObjects.SDK.StreamingFormat.Default);
                @__LocalMessage.FinalizeMessage();
                return this.ClientChannel.AsyncDispatch(@__LocalMessage, @__Callback, @__UserData);
            }
            catch (System.Exception ex) {
                this.@__ClearMessage(@__LocalMessage);
                throw ex;
            }
        }
        public virtual bool EndGuardaFactura(System.IAsyncResult @__AsyncResult) {
            RemObjects.SDK.IMessage @__LocalMessage = ((RemObjects.SDK.IClientAsyncResult)(@__AsyncResult)).Message;
            try {
                bool Result = @__LocalMessage.ReadBoolean("Result");
                return Result;
            }
            finally {
                this.@__ClearMessage(@__LocalMessage);
            }
        }
        public virtual System.Threading.Tasks.Task<bool> GuardaFacturaAsync(TFactura Datos) {
            return System.Threading.Tasks.Task<bool>.Factory.FromAsync(this.BeginGuardaFactura(Datos, null, null), new System.Func<System.IAsyncResult, bool>(this.EndGuardaFactura));
        }
        public virtual System.IAsyncResult BeginFecha(System.AsyncCallback @__Callback, object @__UserData) {
            RemObjects.SDK.IMessage @__LocalMessage = this.@__GetMessage();
            try {
                @__LocalMessage.InitializeRequestMessage(this.ClientChannel, "RPSuiteServer", this.ActiveInterfaceName, "Fecha");
                @__LocalMessage.FinalizeMessage();
                return this.ClientChannel.AsyncDispatch(@__LocalMessage, @__Callback, @__UserData);
            }
            catch (System.Exception ex) {
                this.@__ClearMessage(@__LocalMessage);
                throw ex;
            }
        }
        public virtual System.DateTime EndFecha(System.IAsyncResult @__AsyncResult) {
            RemObjects.SDK.IMessage @__LocalMessage = ((RemObjects.SDK.IClientAsyncResult)(@__AsyncResult)).Message;
            try {
                System.DateTime Result = @__LocalMessage.ReadDateTime("Result");
                return Result;
            }
            finally {
                this.@__ClearMessage(@__LocalMessage);
            }
        }
        public virtual System.Threading.Tasks.Task<System.DateTime> FechaAsync() {
            return System.Threading.Tasks.Task<System.DateTime>.Factory.FromAsync(this.BeginFecha(null, null), new System.Func<System.IAsyncResult, System.DateTime>(this.EndFecha));
        }
        public virtual System.IAsyncResult BeginSPGetFolio(string Datos, System.AsyncCallback @__Callback, object @__UserData) {
            RemObjects.SDK.IMessage @__LocalMessage = this.@__GetMessage();
            try {
                @__LocalMessage.InitializeRequestMessage(this.ClientChannel, "RPSuiteServer", this.ActiveInterfaceName, "SPGetFolio");
                @__LocalMessage.WriteAnsiString("Datos", Datos);
                @__LocalMessage.FinalizeMessage();
                return this.ClientChannel.AsyncDispatch(@__LocalMessage, @__Callback, @__UserData);
            }
            catch (System.Exception ex) {
                this.@__ClearMessage(@__LocalMessage);
                throw ex;
            }
        }
        public virtual int EndSPGetFolio(System.IAsyncResult @__AsyncResult) {
            RemObjects.SDK.IMessage @__LocalMessage = ((RemObjects.SDK.IClientAsyncResult)(@__AsyncResult)).Message;
            try {
                int Result = @__LocalMessage.ReadInt32("Result");
                return Result;
            }
            finally {
                this.@__ClearMessage(@__LocalMessage);
            }
        }
        public virtual System.Threading.Tasks.Task<int> SPGetFolioAsync(string Datos) {
            return System.Threading.Tasks.Task<int>.Factory.FromAsync(this.BeginSPGetFolio(Datos, null, null), new System.Func<System.IAsyncResult, int>(this.EndSPGetFolio));
        }
        public virtual System.IAsyncResult BeginFolio(string Campo, string Serie, System.AsyncCallback @__Callback, object @__UserData) {
            RemObjects.SDK.IMessage @__LocalMessage = this.@__GetMessage();
            try {
                @__LocalMessage.InitializeRequestMessage(this.ClientChannel, "RPSuiteServer", this.ActiveInterfaceName, "Folio");
                @__LocalMessage.WriteAnsiString("Campo", Campo);
                @__LocalMessage.WriteAnsiString("Serie", Serie);
                @__LocalMessage.FinalizeMessage();
                return this.ClientChannel.AsyncDispatch(@__LocalMessage, @__Callback, @__UserData);
            }
            catch (System.Exception ex) {
                this.@__ClearMessage(@__LocalMessage);
                throw ex;
            }
        }
        public virtual int EndFolio(System.IAsyncResult @__AsyncResult) {
            RemObjects.SDK.IMessage @__LocalMessage = ((RemObjects.SDK.IClientAsyncResult)(@__AsyncResult)).Message;
            try {
                int Result = @__LocalMessage.ReadInt32("Result");
                return Result;
            }
            finally {
                this.@__ClearMessage(@__LocalMessage);
            }
        }
        public virtual System.Threading.Tasks.Task<int> FolioAsync(string Campo, string Serie) {
            return System.Threading.Tasks.Task<int>.Factory.FromAsync(this.BeginFolio(Campo, Serie, null, null), new System.Func<System.IAsyncResult, int>(this.EndFolio));
        }
        public virtual System.IAsyncResult BegingetGasolinero(System.AsyncCallback @__Callback, object @__UserData) {
            RemObjects.SDK.IMessage @__LocalMessage = this.@__GetMessage();
            try {
                @__LocalMessage.InitializeRequestMessage(this.ClientChannel, "RPSuiteServer", this.ActiveInterfaceName, "getGasolinero");
                @__LocalMessage.FinalizeMessage();
                return this.ClientChannel.AsyncDispatch(@__LocalMessage, @__Callback, @__UserData);
            }
            catch (System.Exception ex) {
                this.@__ClearMessage(@__LocalMessage);
                throw ex;
            }
        }
        public virtual string EndgetGasolinero(System.IAsyncResult @__AsyncResult) {
            RemObjects.SDK.IMessage @__LocalMessage = ((RemObjects.SDK.IClientAsyncResult)(@__AsyncResult)).Message;
            try {
                string Result = @__LocalMessage.ReadAnsiString("Result");
                return Result;
            }
            finally {
                this.@__ClearMessage(@__LocalMessage);
            }
        }
        public virtual System.Threading.Tasks.Task<string> getGasolineroAsync() {
            return System.Threading.Tasks.Task<string>.Factory.FromAsync(this.BegingetGasolinero(null, null), new System.Func<System.IAsyncResult, string>(this.EndgetGasolinero));
        }
        public virtual System.IAsyncResult BegingetCliente(int ClienteID, System.AsyncCallback @__Callback, object @__UserData) {
            RemObjects.SDK.IMessage @__LocalMessage = this.@__GetMessage();
            try {
                @__LocalMessage.InitializeRequestMessage(this.ClientChannel, "RPSuiteServer", this.ActiveInterfaceName, "getCliente");
                @__LocalMessage.WriteInt32("ClienteID", ClienteID);
                @__LocalMessage.FinalizeMessage();
                return this.ClientChannel.AsyncDispatch(@__LocalMessage, @__Callback, @__UserData);
            }
            catch (System.Exception ex) {
                this.@__ClearMessage(@__LocalMessage);
                throw ex;
            }
        }
        public virtual TCliente EndgetCliente(System.IAsyncResult @__AsyncResult) {
            RemObjects.SDK.IMessage @__LocalMessage = ((RemObjects.SDK.IClientAsyncResult)(@__AsyncResult)).Message;
            try {
                TCliente Result = ((TCliente)(@__LocalMessage.Read("Result", typeof(TCliente), RemObjects.SDK.StreamingFormat.Default)));
                return Result;
            }
            finally {
                this.@__ClearMessage(@__LocalMessage);
            }
        }
        public virtual System.Threading.Tasks.Task<TCliente> getClienteAsync(int ClienteID) {
            return System.Threading.Tasks.Task<TCliente>.Factory.FromAsync(this.BegingetCliente(ClienteID, null, null), new System.Func<System.IAsyncResult, TCliente>(this.EndgetCliente));
        }
        public virtual System.IAsyncResult BeginUpdateVehiculo(TVehiculo Datos, System.AsyncCallback @__Callback, object @__UserData) {
            RemObjects.SDK.IMessage @__LocalMessage = this.@__GetMessage();
            try {
                @__LocalMessage.InitializeRequestMessage(this.ClientChannel, "RPSuiteServer", this.ActiveInterfaceName, "UpdateVehiculo");
                @__LocalMessage.Write("Datos", Datos, typeof(TVehiculo), RemObjects.SDK.StreamingFormat.Default);
                @__LocalMessage.FinalizeMessage();
                return this.ClientChannel.AsyncDispatch(@__LocalMessage, @__Callback, @__UserData);
            }
            catch (System.Exception ex) {
                this.@__ClearMessage(@__LocalMessage);
                throw ex;
            }
        }
        public virtual bool EndUpdateVehiculo(System.IAsyncResult @__AsyncResult) {
            RemObjects.SDK.IMessage @__LocalMessage = ((RemObjects.SDK.IClientAsyncResult)(@__AsyncResult)).Message;
            try {
                bool Result = @__LocalMessage.ReadBoolean("Result");
                return Result;
            }
            finally {
                this.@__ClearMessage(@__LocalMessage);
            }
        }
        public virtual System.Threading.Tasks.Task<bool> UpdateVehiculoAsync(TVehiculo Datos) {
            return System.Threading.Tasks.Task<bool>.Factory.FromAsync(this.BeginUpdateVehiculo(Datos, null, null), new System.Func<System.IAsyncResult, bool>(this.EndUpdateVehiculo));
        }
    }
    public class CoRPDataServiceAsync {
        public static IRPDataService_Async Create(RemObjects.SDK.IMessage message, RemObjects.SDK.IClientChannel clientChannel) {
            return new RPDataService_AsyncProxy(message, clientChannel);
        }
        public static IRPDataService_Async Create(RemObjects.SDK.IRemoteService remoteService) {
            return new RPDataService_AsyncProxy(remoteService);
        }
        public static IRPDataService_Async Create(System.Uri uri) {
            return new RPDataService_AsyncProxy(uri);
        }
        public static IRPDataService_Async Create(string url) {
            return new RPDataService_AsyncProxy(url);
        }
    }
}
